### ISSUE TITLE
URL resolving Issue

### ISSUE THREAD

**Issue by BOberreither** [acdh-oeaw/rs-customisation#17]
In the Person template, tab "Entity IDs", some URLs don't resolve. The cell-template for the ID value selects all values containing "http" and uses them as value in an `a/@href`.
Doesn't work with special characters, e.g.:
`https://fackel.oeaw.ac.at/?p=fackelp47565`
turns into unresolvable
`https://fackel.oeaw.ac.at/?p&#x3D;fackelp47565`
I'm sure there is a simple trick for this ... ?

**Comment by stefanprobst** [comment]
pretty sure this happens because handlebars (the templating engine) html-escapes expressions by default, see https://handlebarsjs.com/guide/expressions.html#html-escaping

wrapping in triple-curly-braces should work: `{{{idUrl.value}}}`
