### ISSUE TITLE
URI resolver

### ISSUE THREAD

**Issue by BOberreither** [acdh-oeaw/rs-customisation#23]
We need a resolver redirecting from SK-URIs to their respective page in SK-RS.

**Comment by acdh** [comment]
Rewriting is performed by ACDH-CH Apache proxy and the domain sk.acdh.oeaw.ac.at. All requests are rewritten to https://semantickraus.acdh.oeaw.ac.at/resource/?uri=https://sk.acdh.oeaw.ac.at/
