### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by BOberreither** [acdh-oeaw/rs-customisation#9]
Distinction between User and Admin: 
User - read only, no authentification needed
Admin - write, authentification needed

**Comment by vronk** [comment]
Here is a response from Diana regarding configuration for anonymous access:

> Here are a few things we do to get this in place. Our setup is mostly ldap plus a local shiro file where we add the credentials for anonymous
> 
> 0. Details here (please scroll all the way down the page)
>     https://docs.google.com/document/d/1aN3wcq88cudMSnWZY58twKkz_dNFoeY9a7xt7HM2CMw/edit 
> 
> 1. In the configuration for docker-compose.yml the section for researchspace platform
>     -Dconfig.environment.enableLocalUsers=true
>     -Dconfig.environment.shiroAuthenticationFilter=authcBasic,anon,authc
> 
> 2. shiro.ini
> [users]
> admin=$shiro1$SHA-256$500000$JWFyxDbrkcdlGl6Xpj02dg==$UYbUG3bHmT8Z4dTeEHToK5WdyvwR9cRefiM/9zRjfr4=,admin,root,query-catalog,repository-admin
> guest=$shiro1$SHA-256$500000$IbH5irWwZzyQlXHZg33GeA==$n+A1vGbmrIxJBBxGcsNn3cz48wDvhBkMbNPcskfAQy4=,guest
> anonymous=$shiro1$SHA-256$500000$LRgzF+Iayekl6VfDVkVWIA==$/s38LlLsNeaGzsD0Z3VTvfurv68HpReieOaNlrcKaPI=,guest
> anonymous-user=$shiro1$SHA-256$500000$IbH5irWwZzyQlXHZg33GeA==$n+A1vGbmrIxJBBxGcsNn3cz48wDvhBkMbNPcskfAQy4=,guest
> 
> [roles]
> root = accounts:*:*, pages:*:*:*, storage:*:*, file:*:*, app:upload, system:restart
> admin = sparql:*:*:*, sparql:graphstore:*, pages:view:*, file:*:*, logs:*:*, ontologies:*:*, storage:upload:*, pages:edit:*:regex(<((?!(http://www.researchspace.org/resource/admin/)).)*>), pages:info:*:*, api:config:*:*:*, namespaces:*, forms:ldp:*, forms:sparql:*, caches:*:invalidate, services:*, ui:component:view:mp:sparql:query:editor:select:repository, ui:page:view:toolbar:*, api:ldp:*, job:*:*, proxy:*, storage:view-config:*, app:view-config:*
> guest = sparql:default:query:*, sparql:assets:query:*, pages:view:regex(<((?!(http://www.researchspace.org/resource/admin/)).)*>), api:config:environment:resourceUrlMapping:read, api:config:ui:*:read, api:config:global:homePage:read, ui:page:view:toolbar:*, api:ldp:container:<http://www.researchspace.org/resource/system/queryContainer>:read:any, api:ldp:container:<http://www.researchspace.org/resource/system/queryTemplateContainer>:read:any, api:ldp:container:<http://www.researchspace.org/resource/system/ontodiaDiagramContainer>:read:any
> query-catalog = api:ldp:container:<http://www.researchspace.org/resource/system/queryContainer>:*:any, api:ldp:container:<http://www.researchspace.org/resource/system/queryTemplateContainer>:*:any
> repository-admin=repository-config:*:*
> 
> 3. passwords 
> https://github.com/researchspace/researchspace/tree/master/dist/docker/platform there is shiro-tools-hasher-1.3.2-cli.jar:
> java -jar ./shiro-tools-hasher-1.3.2-cli.jar -f shiro1 -a sha-256 --iterations 500000 -gs yourpassword 
> 
> 4. Other info that may be helpful:
>    https://drive.google.com/drive/folders/1siQXDEjbJNWLQoIcIuVJngSBA99LADoi
> 

@dpancic could you try to apply it on SK instance?

**Comment by acdh** [comment]
Anonymous user is enabled by adding it to /srv/shiro.ini over the Rancher secrets and by adding following config to Researchespace PLATFORM_OPTS ENV variables:
-Dconfig.environment.enableLocalUsers=true
-Dconfig.environment.shiroAuthenticationFilter=authcBasic,anon,authc
